project:
  type: website
  output-dir: docs

website:
  title: "Dona Lontok"
  favicon: me.png

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.pdf
        text: CV
      - text: Assignments
        menu:
        - href: Assignment1.qmd
          text: Assignment 1
        - href: labs\Lab01.qmd
          text: Assignment 2 - Lab01
        - href: labs\Lab02.qmd
          text: Assignment 2 - Lab02
        - href: labs\Lab03.qmd
          text: Assignment 3 - Lab03
      - text: Paper Reviews
        menu:
        - href: ToExplainOrToPredict.qmd
          text: To Explain Or To Predict
      - href: project.qmd
        text: Project

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

