project:
  type: website
  output-dir: docs

website:
  title: "Dona Lontok"
  favicon: me.png

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV
      - text: Assignments
        menu:
        - href: Assignment1.qmd
          text: Assignment1
        - href: labs\Lab01.qmd
          text: Assignment2-Lab01
        - href: labs\Lab02.qmd
          text: Assignment2-Lab02
        - href: assignment3.qmd
          text: Assignment3
      - text: Paper Reviews
        menu:
        - href: ToExplainOrToPredict.qmd
          text: To Explain Or To Predict

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual

