---
title: "To Explain or To Predict?"
---

The article, To Explain or To Predict? written by Galit Shmueli provides a thorough explanation of the two distinct goals of modeling which are either explanatory or predictive. Explanatory models, which are typically used in the science and social fields, focus on the causal relationship of the predictors and the result by attempting to prove a theory. Predictive models, however, or more focused on achieving accurate predictions based on association of predictors and result, and not their causal relationship. The author goes on to say that functions used by predictive models don't even need to match the true function, unlike explanatory models that attempt to create a model as close as possible to the truth. The author discusses in great detail the differences in approach between the two goals when performing the different steps of modeling from design and data collection all the way to model use and reporting. This paper written in 2010 is supportive of the observation by Leo Breiman who wrote the article \'Statistical Modeling: The Two Cultures\' in 2001. In this paper, Breiman also described two goals when analyzing data, which are prediction and information. The latter pertains to understanding the structure of the relationship between the inputs and output which is congruent to the explanatory goal that Shmueli described. Breiman pointed out the increasing availability of data, which he noted as one of the reasons why statisticians should focus on the problem and the data available instead of finding the right model. Similarly, Shmueli\'s stresses the accelerated growth in social, environmental and technology fields, and the necessity to create new theories that reflect new realities. Both Breiman and Shmueli pointed out that just focusing on explanatory goals, using old techniques like regression modeling, can lead to incorrect conclusions. Scientists in different fields should learn to adapt diverse tools such as algorithmic modeling in order to keep up with advancing realities. As Shmueli concluded, advocacy of both explanatory and predictive modeling and the use of tools and knowledge to achieve both goals are essential for scientific progress.
